services:
    filemanager_configuration:
        class: Artgris\Bundle\MediaBundle\Service\FileManagerConfigurationService
        tags:
            - { name: twig.extension }
        arguments: ['@parameter_bag']

#    file_type_service:
#        class: Artgris\Bundle\FileManagerBundle\Service\FileTypeService
#        arguments: ['@router']
#        public: true
