services:
    filemanager_configuration:
        class: Artgris\Bundle\MediaBundle\Service\FileManagerConfigurationService
        tags:
            - { name: twig.extension }
        arguments: ['@parameter_bag']

    twig.extension.gimage:
        class: Artgris\Bundle\MediaBundle\Service\GImageTwig
        arguments: ['@image.handling']
        tags:
            - { name: twig.extension }