services:
    filemanager_configuration:
        class: Artgris\Bundle\MediaBundle\Service\FileManagerConfigurationService
        tags:
            - { name: twig.extension }
        arguments: ['@artgris_bundle_file_manager.service.filemanager_service', '@parameter_bag']

    twig.extension.gimage:
        class: Artgris\Bundle\MediaBundle\Service\GImageTwig
        arguments: ['@image.handling']
        tags:
            - { name: twig.extension }