services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Artgris\Bundle\MediaBundle\Controller\:
        resource: '../../Controller/*'


    filemanager_configuration:
        class: Artgris\Bundle\MediaBundle\Service\FileManagerConfigurationService
        tags:
            - { name: twig.extension }
        arguments: ['@Artgris\Bundle\FileManagerBundle\Service\FilemanagerService', '@parameter_bag']

    twig.extension.rs_image:
        class: Artgris\Bundle\MediaBundle\Service\RSlashTwig
        tags:
            - { name: twig.extension }